services:

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
      MONGO_COLLECTION_NAME: ${MONGO_COLLECTION_NAME}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGO_HOST}:${MONGO_PORT}:27017
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]

volumes:
  data:
